### ISSUE TITLE
Bug: Fixing OG Image Generation 📸

### ISSUE THREAD

**Issue by MykalMachon** [MykalMachon/mykal.codes#14]
## Summary of issue
It takes too dang long to generate OG images, so they often don't show up in actual cards. 
I want to resolve this, by generating a photo *one time* on initial request, setting the file name to the hash of inputs, and [uploading it to cloudflare](https://cloudinary.com/documentation/upload_images#upload_via_a_base_64_data_uri). 

## Todos
- [x] Setup Cloudflare API key
- [x] Create function to upload Base64 image
- [x] Setup authentication/limiting of image creation 
- [ ] Test and deploy

**Comment by MykalMachon** [comment]
This was broken due to dependency hell issues with the aws-lambda-chrome package I'm using to generate OG images. 
I'm going to have to re-evaluate the approach. It may be worth looking into a post-build step where images are generated and saved in the actual server folders.
