### ISSUE TITLE
Feature: tags on posts 🏷️

### ISSUE THREAD

**Issue by MykalMachon** [MykalMachon/Mykal.Codes#15]
## Summary of issue
I want to have tags listed on the post page, and on the post list page. 
This should make things a little easier to parse on the site. 

## Todos 
- [ ] Remove *requirement* for tags on posts
- [ ] Add tags to "large" <PostList />
- [ ] Add tags to "medium" <PostList /> 
- [ ] Add tags to the actual post page
