### ISSUE TITLE
Feature: Dark Mode 🌑

### ISSUE THREAD

**Issue by MykalMachon** [MykalMachon/mykal.codes#19]
## Summary of PR
You know what it is... we need dark mode on the site. 

## Todos
- [x] Checkout Andy Bell's post on dark mode in js
- [x] implement dark mode with an ugly button
- [x] implement dark mode with a pretty button

**Comment by MykalMachon** [comment]
Finished this awhile ago.
