### ISSUE TITLE
View tracker and like button

### ISSUE THREAD

**Issue by MykalMachon** [MykalMachon/mykal.codes#34]
## Summary
I think it'd be cool to set up a "view tracker" similar to those that you'd see in early web1.0 days "this page has x views!", as well as a like button which would let people react / like to a post if they'd like to. 

## Things todo
- [x] Find a good old kv data store to use (cloudflare KV?)
- [x] Build out serverless API routes to insert data into the keystore
  - [x] serverless API for likes
  - [x] serverless API for views
- [x] Implement the UI to call the APIs
  - [x] like / reaction button
  - [x] view counter that will call the view count API

**Comment by MykalMachon** [comment]
One thing I'm not loving about this so far is that there's no good way to store the cloudflare workers code in my repo and deploy that alongside these other components... not ideal for sure.
