### ISSUE TITLE
Feature: OG Image Generator

### ISSUE THREAD

**Issue by MykalMachon** [MykalMachon/Mykal.Codes#5]
## Summary of Issue
I've started working on a OG image generator here and would like to port it to Netlify Functions, and use it for this site. 

## Todos
- [x] Port OG image generator over 
- [x] Create template for posts pages
- [x] Create template for non-post pages
- [ ] test and deploy 🚀
