### ISSUE TITLE
Feature: tags on posts

### ISSUE THREAD

**Issue by MykalMachon** [MykalMachon/Mykal.Codes#9]
## Summary of Issue
need to add tags on posts, and tags pages so I can keep things organized on the blog as it continues to grow. 

## Todos
- [ ] add tags array to all posts
- [ ] add tags pages / tag page generator 
- [ ] add list of all tags to the posts page
